title: MCUL
description: Simplify the logic behind organizing atoms into molecules
show_downloads: true
ga_tracking: UA-78556187-11
remote_theme: pmarsceill/just-the-docs
author: "Russell Steadman"
aux_links:
    "NPM":
      - "https://www.npmjs.com/package/mcul"
    "Github":
      - "https://github.com/teamtofu/mcul"
author_email: steadman.21@osu.edu
footer_content: "MCUL v0.1.0-alpha3. Copyright &copy; 2020 Russell Steadman. Distributed under an MIT license."