title: MCUL
description: Parse text-based representations of chemicals into usable information.
show_downloads: true
google_analytics: UA-78556187-11
theme: jekyll-theme-cayman
author: Russell Steadman
author_email: steadman.21@osu.edu